plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
remote_theme: jekyll/minima@6b9b78dad3e5c9f733c901e10287465735b36169
include:
  - BuildUbuntu.md
  - Customformats.md
  - FAQ.md
  - Hdroutput.md
  - index.md
  - Localediting.md
  - Luts.md
  - Pipeline.md
  - Quickstart.md
  - Reference.md
  - Session.md
  - Shapes.md
  - Shortcuts.md
  - Usercommands.md
  - Watermark.md
  - Documentation.md
  - Downloads.md
header_pages:
  - index.md
  - Documentation.md
  - Downloads.md
  - Links.md
