plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

remote_theme: jekyll/minima

include:
  - BuildUbuntu.md
  - Customformats.md
  - FAQ.md
  - Hdroutput.md
  - index.md
  - Localediting.md
  - Luts.md
  - Pipeline.md
  - Quickstart.md
  - Reference.md
  - Session.md
  - Shapes.md
  - Shortcuts.md
  - Usercommands.md
  - Watermark.md
  - Documentation.md
  - Downloads.md

header_pages:
  - index.md
  - Documentation.md
  - Downloads.md
